version: '3.8'

services:
  # API Gateway - Single entry point
  nginx:
    image: nginx:latest
    configs:
      - source: denops-nginx
        target: /etc/nginx/nginx.conf

    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=edge_public"
        - "traefik.http.routers.denopslocal.rule=Host(`denops.internal`)"
        - "traefik.http.routers.denopslocal.entrypoints=websecure"
        - "traefik.http.routers.denopslocal.tls=true"
        - "traefik.http.routers.denopslocal.middlewares=sec@swarm"
        - "traefik.http.services.denopslocal.loadbalancer.server.port=80"
        - "traefik.http.middlewares.sec.headers.framedeny=true"
        - "traefik.http.middlewares.sec.headers.stsseconds=63072000"
        - "traefik.http.middlewares.sec.headers.stsincludesubdomains=true"
        - "traefik.http.middlewares.sec.headers.stspreload=true"
        - "traefik.http.middlewares.sec.headers.contenttypenosniff=true"
        - "traefik.http.middlewares.sec.headers.browserxssfilter=true"
        - "denops.config.version=${CONFIG_VERSION_NGINX}"
    networks:
      - edge_public # Connect to Traefik
      - backend  # Can reach backend services


  auth:
    image: registry.octagon.home/animal-pride/denops-auth:${IMAGE_TAG}
    configs:
      - source: denops-config
        target: /opt/denops-auth/config.yml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    secrets:
      - denops_auth_db_password
      - denops_auth_jwt_secret
    environment:
      - DENOPS_AUTH_DB_PASSWORD_FILE=/run/secrets/denops_auth_db_password
      - DENOPS_AUTH_JWT_SECRET_FILE=/run/secrets/denops_auth_jwt_secret
    deploy:
      # replicas: 1  # Reduce to 1 for debugging  
      # restart_policy:
      #   condition: none
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        - "denops.config.version=${CONFIG_VERSION_APP}"
    networks:
      - backend  # Only backend network
      - infra_internal  # Connect to internal network for db and message queue


  core:
    image: registry.octagon.home/animal-pride/denops-core:${IMAGE_TAG}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    configs:
      - source: denops-config
        target: /opt/denops-core/config.yml
    environment:
      - DENOPS_CORE_DB_PASSWORD_FILE=/run/secrets/denops_core_db_password
      - DENOPS_INTERNAL_TOKEN_FILE=/run/secrets/denops_internal_token
    secrets:
      - denops_core_db_password
      - denops_internal_token
    deploy:
      # replicas: 1  # Reduce to 1 for debugging  
      # restart_policy:
      #   condition: none
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
      labels:
        - "denops.config.version=${CONFIG_VERSION_APP}"
    networks:
      - backend  # Only backend network
      - infra_internal  # Connect to internal network for db and message queue
  events:
    image: registry.octagon.home/animal-pride/denops-events:${IMAGE_TAG}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    configs:
      - source: denops-config
        target: /opt/denops-events/config.yml
    environment:
      - DENOPS_EVENTS_DB_USER_FILE=/run/secrets/denops_events_db_user
      - DENOPS_EVENTS_DB_PASSWORD_FILE=/run/secrets/denops_events_db_password
      - DENOPS_INTERNAL_TOKEN_FILE=/run/secrets/denops_internal_token
      - DENOPS_EVENTS_RABBITMQ_USER_FILE=/run/secrets/denops_events_rabbitmq_user
      - DENOPS_EVENTS_RABBITMQ_PASSWORD_FILE=/run/secrets/denops_events_rabbitmq_password
    secrets:
      - denops_events_db_user
      - denops_events_db_password
      - denops_internal_token
      - denops_events_rabbitmq_user
      - denops_events_rabbitmq_password
    deploy:
      # replicas: 1  # Reduce to 1 for debugging  
      # restart_policy:
      #   condition: none
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
      labels:
        - "denops.config.version=${CONFIG_VERSION_APP}"
    networks:
      - backend  # Only backend network
      - infra_internal # Connect to internal network for db and message queue
  assets:
    image: registry.octagon.home/animal-pride/assets:${IMAGE_TAG}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    configs:
      - source: denops-config
        target: /opt/assets/config.yml
    environment:
      - DENOPS_CORE_DB_PASSWORD_FILE=/run/secrets/denops_core_db_password
    secrets:
      - denops_core_db_password
    volumes:
      - assets:/asset_source
    deploy:
      # replicas: 1  # Reduce to 1 for debugging  
      # restart_policy:
      #   condition: none
      replicas: 6
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
      labels:
        - "denops.config.version=${CONFIG_VERSION_APP}"
    networks:
      - backend  # Only backend network
      - infra_internal  # Connect to internal network for db and message queue

  ui:
    image: registry.octagon.home/animal-pride/denops-ui:${IMAGE_TAG}
    healthcheck:
      test: ["CMD-SHELL", "curl -v -f http://localhost/ || (echo 'Healthcheck failed' && exit 1)"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    deploy:
      # replicas: 1  # Reduce to 1 for debugging  
      # restart_policy:
      #   condition: none
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
      restart_policy:
        condition: on-failure
      labels:
        - "denops.config.version=${CONFIG_VERSION_APP}"
    networks:
      - backend  # Only backend network

networks:
  edge_public:
    external: true
  infra_internal:
    external: true
  backend:
    driver: overlay
    attachable: true  # Allows external containers to connect for testing

configs:
  denops-config:
    name: denops-config-${CONFIG_VERSION_APP}
    external: true
  denops-nginx:
    name: denops-nginx-${CONFIG_VERSION_NGINX}
    external: true

volumes:
  assets:
    external: true

secrets:
  denops_auth_db_password:
    external: true
  denops_auth_jwt_secret:
    external: true
  denops_core_db_password:
    external: true
  denops_internal_token:
    external: true
  denops_events_db_user:
    external: true
  denops_events_db_password:
    external: true
  denops_events_rabbitmq_user:
    external: true
  denops_events_rabbitmq_password:
    external: true    